### ISSUE TITLE
Kodi not closing with Andromeda

### ISSUE THREAD

**Issue by ghost** [Tgxcorporation/skin.andromeda#5]
On requestion Kodi close Kodi hangs.

Switching to Estuary kodi closes fine. 

Debug:

https://paste.ubuntu.com/p/kCjg38Tx2V/

**Comment by Tgxcorporation** [comment]
some addons are crashing:

failed to stop plugin.video.discovery-g (may have ended)
failed to stop plugin.video.sirius (may have ended)
failed to stop service.xbmc.versioncheck (may have ended)

it does not depend on the skin

**Comment by ghost** [comment]
I thought this when going through the debug log.

However swapping to estuery allows quit to work flawlessy, the same (may have ended) is in the kodi.old.log then.

Could it be skin.helper.service causing it?

Thats used by this skin but not by estuary.

**Comment by Tgxcorporation** [comment]
The default skin does not use the same addons. I would at least wait for a beta version of Leia and for updated addons.

**Comment by ghost** [comment]
Ok, thank you. Great work on the skin btw. Very clean and very professional. Thank you for your work.
