### ISSUE TITLE
Animated Images Not Setting

### ISSUE THREAD

**Issue by ghost** [Tgxcorporation/skin.andromeda#6]
When adding Movies to the local db you can right click and Select Animated Artwork.

(This may be through skin.helper.service)

On setting the animated artwork the skin does not show the newly selected artowrk, it continues to show the basic artwork pulled by tmdb.

Would this be an issue you are familiar with?

Any additional info I can provide please let me know. I know animated artwork is supported in many skins so I would assume there is a missing listitem infolabel to get the new artwork.

**Comment by Tgxcorporation** [comment]
The skin does not support animated artwork.
It's not so easy. 
Added to my to-do list.

Tgx
