### ISSUE TITLE
KODI 18 LEIA RC5 no longer compatible 

### ISSUE THREAD

**Issue by adamforeman** [Tgxcorporation/skin.andromeda#7]
As of now, Andromeda skin is no longer compatible and is disabled.

Please can you advise if you are willing to update your amazing skin? 

Many thanks 

Ad

**Comment by Tgxcorporation** [comment]
I’m going to post an update for the final Leia version

**Comment by adamforeman** [comment]
Thank you very much, I appreciate your hard work on this skin. It was my go to skin before RC5 disabled it

Cheers

**Comment by Tgxcorporation** [comment]
It's working with the latest commit.

**Comment by trustin** [comment]
When would it be released to the official addon repository? It was not there a few days ago and I had to install it from ZIP.
